### ISSUE TITLE
Please update document

### ISSUE THREAD

**Issue by sandaemc** [CodingAvenue/ca-school#36]
Please update document about differentiating single/multiple selection in writing content to the Wiki.

Multiple Selection -> Single Selection -> Radio Buttons
Multiple Choice -> Multiple Selection -> Checkboxes

@nlabrador @cerilacanda fyi

**Comment by maraoarao** [comment]
@sandaemc What do you mean by this? Can you please give me an example on how to do it? Thanks.

**Comment by sandaemc** [comment]
This repo has "Wiki" tab. Go to it and update the Question Format/Example page.

**Comment by maraoarao** [comment]
@sandaemc Thanks

Close this issue. Wiki document was already updated. Type MC was changed to SS which means `Single Selection`.
